language: bash
sudo: false

matrix:
  include:
    - env: infra=ec2-0
    - env: infra=ec2-1
    - env: infra=ec2-2
    - env: infra=ec2-3
    - env: infra=ec2-4
    - env: infra=ec2-5

install: true
script: echo 'Hi'
